trigger:
- master

pool:
  name: Default

steps:
- script: echo "Hello, it's my Azure DevOps App"
  displayName: 'Run echo command'

- script: mvn clean install
  displayName: 'Build with maven'

- script: java -jar target/mav3-0.0.1-SNAPSHOT.jar
  displayName: 'Run jar file of My mav3 App'